name : jsGrid
brand : jsGrid
description : Lightweight Grid jQuery Plugin
keyword: 
url : http://js-grid.com
email : tabalinas@gmail.com
twitter : artem_tabalin
github : tabalinas
author: Artem Tabalin
analytics: UA-44114514-5
year: 2015
markdown: kramdown
version: 1.5.0